name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  clippy_nightly:
    name: Clippy check on nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: clippy

      - name: Run Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features "union_optimizations doc_cfg"
        env:
          RUSTFLAGS: -D warnings
      
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features "union_optimizations doc_cfg"
        env:
          RUSTFLAGS: -D warnings
  
  clippy_stable:
    name: Clippy check on stable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: clippy

      - name: Run Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
        env:
          RUSTFLAGS: -D warnings
      
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          RUSTFLAGS: -D warnings

