name: Checks and tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  stable:
    name: On stable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install Rust 1.46
        uses: actions-rs/toolchain@v1
        with:
            toolchain: "1.46.0"
            profile: minimal
            override: true
            components: clippy

      - name: Run Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          # Clippy on 1.46 doesn't have some lints from the latest nightly that we use, so we
          # disable warning about that altogether, since we still test for those on the nightly.
          args: "-- -A clippy::unknown_clippy_lints"
        env:
          RUSTFLAGS: -D warnings
      
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          RUSTFLAGS: -D warnings
  
  nightly:
    name: On nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            profile: minimal
            override: true
            components: clippy

      - name: Run Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features "union_optimizations doc_cfg"
        env:
          RUSTFLAGS: -D warnings
      
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features "union_optimizations doc_cfg"
        env:
          RUSTFLAGS: -D warnings
